"""Catálogo y definiciones de reglas de estilo de cátedra en GAFF, alineado con p1-apunte/reglas."""

from __future__ import annotations

from typing import Any, Dict

CATALOGO_REGLAS: Dict[str, Dict[str, Any]] = {
    # 0x00XXh: Sintaxis Básica y Nomenclatura
    "0x0000h": {
        "codigo": "0x0000h",
        "alias": "GAFF000",
        "titulo": "La claridad y prolijidad son de máxima importancia",
        "descripcion": "El código debe ser claro y fácil de entender para cualquier lector. Un código limpio y prolijo previene errores y facilita el mantenimiento.",
        "ejemplo_correcto": "int i = 0;\nwhile (i < limite) {\n    printf(\"%d\", i);\n    i++;\n}",
        "ejemplo_incorrecto": "for (int i=0,j=10;i<j;i++,j--) { printf(\"%d\", i+j); }",
        "autofix": "No",
    },
    "0x0001h": {
        "codigo": "0x0001h",
        "alias": "GAFF011",
        "titulo": "Los identificadores deben ser descriptivos",
        "descripcion": "Los nombres de variables y argumentos deben reflejar con precisión su propósito. Evitá variables de una sola letra (salvo índices canónicos i, j, k, n, x, y, z, f, c, r).",
        "ejemplo_correcto": "int precio_total = obtener_precio();",
        "ejemplo_incorrecto": "int a = obtener_precio();",
        "autofix": "No",
    },
    "0x0002h": {
        "codigo": "0x0002h",
        "alias": "GAFF012",
        "titulo": "Una declaración de variable por línea",
        "descripcion": "Declarar cada variable en una línea separada para facilitar comentarios y legibilidad.",
        "ejemplo_correcto": "int primer_valor;\nint segundo_valor;",
        "ejemplo_incorrecto": "int primer_valor, segundo_valor, tercer_valor;",
        "autofix": "No",
    },
    "0x0003h": {
        "codigo": "0x0003h",
        "alias": "GAFF013",
        "titulo": "Siempre debés inicializar las variables a un valor conocido",
        "descripcion": "Inicializar las variables locales al declararlas para evitar valores residuales del stack.",
        "ejemplo_correcto": "int contador = 0;\nstruct datos_t d = {0};",
        "ejemplo_incorrecto": "int contador;\nstruct datos_t d;",
        "autofix": "No",
    },
    "0x0004h": {
        "codigo": "0x0004h",
        "alias": "GAFF007",
        "titulo": "Un espacio antes y después de cada operador binario y palabra clave",
        "descripcion": "Debe dejarse un espacio en blanco entre la palabra clave de control y el paréntesis ('if (', 'for (', 'while (', 'switch (') y alrededor de operadores binarios.",
        "ejemplo_correcto": "if (x > 0) {\n    total = valor1 + valor2;\n}",
        "ejemplo_incorrecto": "if(x>0){\n    total=valor1+valor2;\n}",
        "autofix": "Sí",
    },
    "0x0005h": {
        "codigo": "0x0005h",
        "alias": "GAFF010",
        "titulo": "Cada bloque debe tener una indentación de cuatro espacios (sin tabs ni trailing)",
        "descripcion": "La indentación debe ser exactamente de 4 espacios respecto al contenedor. No se permiten tabuladores duros (\\t) ni espacios sobrantes al final de línea.",
        "ejemplo_correcto": "void funcion(void)\n{\n    int x = 10;\n}",
        "ejemplo_incorrecto": "void funcion(void){\n\tint x = 10;   \n}",
        "autofix": "Sí",
    },
    "0x0006h": {
        "codigo": "0x0006h",
        "alias": "GAFF014",
        "titulo": "El asterisco de los punteros debe declararse junto al identificador",
        "descripcion": "Declarar el asterisco junto al nombre de la variable ('int *ptr') y no junto al tipo ('int* ptr').",
        "ejemplo_correcto": "int *ptr;\nchar *nombre;",
        "ejemplo_incorrecto": "int* ptr;\nchar* nombre;",
        "autofix": "Sí",
    },
    "0x0007h": {
        "codigo": "0x0007h",
        "alias": "GAFF001",
        "titulo": "Los argumentos y variables locales deben usar snake_case en minúsculas",
        "descripcion": "Todos los identificadores de variables y argumentos deben estar escritos en snake_case en minúsculas, evitando camelCase o PascalCase.",
        "ejemplo_correcto": "int calcular_promedio(int *vector_numeros, size_t longitud_total);",
        "ejemplo_incorrecto": "int calcularPromedio(int *vectorNumeros, size_t LongitudTotal);",
        "autofix": "No",
    },
    "0x0008h": {
        "codigo": "0x0008h",
        "alias": "GAFF015",
        "titulo": "Las constantes deben nombrarse en MAYUSCULAS_SNAKE_CASE",
        "descripcion": "Las constantes (#define y const) deben escribirse enteramente en MAYUSCULAS_SNAKE_CASE.",
        "ejemplo_correcto": "#define BUFFER_MAX 1024\nconst int DIAS_SEMANA = 7;",
        "ejemplo_incorrecto": "#define buffer_max 1024\nconst int diasSemana = 7;",
        "autofix": "No",
    },
    "0x0009h": {
        "codigo": "0x0009h",
        "alias": "GAFF009",
        "titulo": "Las líneas de código no deben exceder los 79-80 caracteres",
        "descripcion": "Las líneas de código no deben superar los 80 caracteres de ancho para evitar desplazamiento horizontal.",
        "ejemplo_correcto": "printf(\"Mensaje largo dividido \"\n       \"en dos líneas continuas.\\n\");",
        "ejemplo_incorrecto": "printf(\"Este es un mensaje de texto extremadamente largo que supera los ochenta caracteres en una sola línea.\\n\");",
        "autofix": "No",
    },
    "0x000Ah": {
        "codigo": "0x000Ah",
        "alias": "GAFF016",
        "titulo": "Escribí comentarios que expliquen el 'porqué', no el 'qué'",
        "descripcion": "Los comentarios deben aportar valor justificando decisiones de diseño y no repetir lo evidente ni estar vacíos.",
        "ejemplo_correcto": "// Usamos índice inverso porque el último byte define la paridad del paquete\nfor (size_t i = len - 1; i < len; i--)",
        "ejemplo_incorrecto": "// Incrementa i en 1\ni++;",
        "autofix": "No",
    },
    "0x000Bh": {
        "codigo": "0x000Bh",
        "alias": "GAFF017",
        "titulo": "Las llaves deben ubicarse en líneas independientes según el estilo Allman",
        "descripcion": "Ubicar las llaves de apertura y cierre en líneas separadas alineadas con la instrucción de control.",
        "ejemplo_correcto": "if (x > 0)\n{\n    return x;\n}",
        "ejemplo_incorrecto": "if (x > 0) {\n    return x;\n}",
        "autofix": "No",
    },

    # 0x10XXh: Estructuras de Control y Lazos
    "0x1001h": {
        "codigo": "0x1001h",
        "alias": "GAFF018",
        "titulo": "Todas las estructuras de control deben utilizar llaves",
        "descripcion": "Las sentencias if, else, for, while deben incluir siempre llaves {}, incluso para bloques de una sola línea.",
        "ejemplo_correcto": "if (x > 0)\n{\n    x++;\n}",
        "ejemplo_incorrecto": "if (x > 0)\n    x++;",
        "autofix": "No",
    },
    "0x1002h": {
        "codigo": "0x1002h",
        "alias": "GAFF019",
        "titulo": "Evitá continue y break descontrolado; preferí banderas lógicas",
        "descripcion": "El uso de continue está estrictamente prohibido y break debe reservarse para simplificaciones claras o dentro de switch.",
        "ejemplo_correcto": "bool seguir = true;\nwhile (i < 10 && seguir) { ... }",
        "ejemplo_incorrecto": "for (int i = 0; i < 10; i++) { if (i == 4) continue; }",
        "autofix": "No",
    },
    "0x1003h": {
        "codigo": "0x1003h",
        "alias": "GAFF020",
        "titulo": "Utilizá for para conteo definido y while para lazos lógicos",
        "descripcion": "No forzar lecturas interactivas o lazos indefinidos (for(;;)) dentro del encabezado for.",
        "ejemplo_correcto": "while (numero != 0) { scanf(\"%d\", &numero); }",
        "ejemplo_incorrecto": "for (scanf(\"%d\", &n); n != 0; scanf(\"%d\", &n)) { ... }",
        "autofix": "No",
    },
    "0x1004h": {
        "codigo": "0x1004h",
        "alias": "GAFF021",
        "titulo": "Las condiciones complejas deben ser simplificadas o comentadas",
        "descripcion": "Dividir expresiones booleanas complejas con múltiples operadores usando variables intermedias explicativas.",
        "ejemplo_correcto": "bool es_valido = usuario_activo && tiene_permisos;\nif (es_valido) { ... }",
        "ejemplo_incorrecto": "if ((usuario_activo && tiene_permisos && !mantenimiento) || (es_admin && clave_maestra))",
        "autofix": "No",
    },
    "0x1005h": {
        "codigo": "0x1005h",
        "alias": "GAFF022",
        "titulo": "Evitá condiciones ambiguas basadas en truthiness",
        "descripcion": "Comparar explícitamente contra NULL, contra '\\0' o contra 0 en lugar de confiar en conversiones booleanas implícitas.",
        "ejemplo_correcto": "if (ptr != NULL)\nif (caracter == '\\0')",
        "ejemplo_incorrecto": "if (ptr)\nif (!caracter)",
        "autofix": "No",
    },
    "0x1006h": {
        "codigo": "0x1006h",
        "alias": "GAFF008",
        "titulo": "No utilizar la instrucción goto",
        "descripcion": "El uso de 'goto' está estrictamente prohibido en el paradigma de programación estructurada de la cátedra.",
        "ejemplo_correcto": "Utilizar estructuras de bucle y retornos limpios estructurados.",
        "ejemplo_incorrecto": "goto cleanup;",
        "autofix": "No",
    },
    "0x1007h": {
        "codigo": "0x1007h",
        "alias": "GAFF023",
        "titulo": "No utilizar el operador condicional (ternario) ?:",
        "descripcion": "El operador ternario complica la lectura; utilizá if-else estructurado.",
        "ejemplo_correcto": "if (a > b) {\n    res = a;\n} else {\n    res = b;\n}",
        "ejemplo_incorrecto": "res = (a > b) ? a : b;",
        "autofix": "No",
    },
    "0x1008h": {
        "codigo": "0x1008h",
        "alias": "GAFF024",
        "titulo": "Toda instrucción switch debe incluir un caso default",
        "descripcion": "Incluir siempre default: al final de un bloque switch para manejar estados no previstos.",
        "ejemplo_correcto": "switch (cmd) {\n    case 1: ... break;\n    default: ... break;\n}",
        "ejemplo_incorrecto": "switch (cmd) {\n    case 1: ... break;\n}",
        "autofix": "No",
    },

    # 0x20XXh: Funciones y Modularización
    "0x2001h": {
        "codigo": "0x2001h",
        "alias": "GAFF025",
        "titulo": "Usar cláusulas de guarda para evitar anidación profunda",
        "descripcion": "Validar precondiciones y salir tempranamente para evitar código en flecha (anidación > 3 niveles).",
        "ejemplo_correcto": "if (s == NULL) return -1;\nif (s->activo == false) return -1;",
        "ejemplo_incorrecto": "if (s != NULL) { if (s->activo) { if (s->val > 0) { ... } } }",
        "autofix": "No",
    },
    "0x2002h": {
        "codigo": "0x2002h",
        "alias": "GAFF026",
        "titulo": "Las funciones auxiliares no deben contener printf o scanf",
        "descripcion": "Separar la lógica computacional del código de entrada/salida por consola.",
        "ejemplo_correcto": "float calcular_iva(float monto) { return monto * 0.21f; }",
        "ejemplo_incorrecto": "void calcular_iva(float monto) { printf(\"IVA: %f\\n\", monto * 0.21f); }",
        "autofix": "No",
    },
    "0x2003h": {
        "codigo": "0x2003h",
        "alias": "GAFF027",
        "titulo": "Todas las funciones deben incluir documentación completa",
        "descripcion": "Documentar funciones con @brief, @param y @return en formato Doxygen.",
        "ejemplo_correcto": "/**\n * @brief Suma dos enteros.\n * @param a Primer sumando.\n * @param b Segundo sumando.\n * @return Resultado de la suma.\n */",
        "ejemplo_incorrecto": "int suma(int a, int b);",
        "autofix": "No",
    },
    "0x2004h": {
        "codigo": "0x2004h",
        "alias": "GAFF003",
        "titulo": "No se permite el uso de variables globales mutables",
        "descripcion": "No se permite el uso de variables globales mutables fuera del alcance de las funciones. Toda comunicación debe ser vía parámetros y retornos.",
        "ejemplo_correcto": "const double PI = 3.14159265;\n#define BUFFER_MAX 1024",
        "ejemplo_incorrecto": "int contador_global = 0;",
        "autofix": "No",
    },
    "0x2005h": {
        "codigo": "0x2005h",
        "alias": "GAFF004",
        "titulo": "Cada función debe tener una única responsabilidad (<= 50 líneas)",
        "descripcion": "Las funciones no deben exceder las 50 líneas de código para garantizar modularidad, legibilidad y responsabilidad única.",
        "ejemplo_correcto": "Dividir funciones complejas en funciones auxiliares privadas (static).",
        "ejemplo_incorrecto": "Una función procesar_todo() de 120 líneas continuas.",
        "autofix": "No",
    },
    "0x2006h": {
        "codigo": "0x2006h",
        "alias": "GAFF028",
        "titulo": "Una aserción por cada función de prueba",
        "descripcion": "Modularizar las pruebas unitarias enfocando cada test en un caso atómico.",
        "ejemplo_correcto": "void test_suma_positivos() { assert(sumar(2, 2) == 4); }",
        "ejemplo_incorrecto": "void test_todo() { assert(sumar(2,2)==4); assert(restar(4,2)==2); assert(mult(2,3)==6); }",
        "autofix": "No",
    },
    "0x2007h": {
        "codigo": "0x2007h",
        "alias": "GAFF029",
        "titulo": "Mantené el alcance de las variables al mínimo posible",
        "descripcion": "Declarar las variables en el bloque más interno donde sean utilizadas.",
        "ejemplo_correcto": "for (int i = 0; i < n; i++) { ... }",
        "ejemplo_incorrecto": "int i; // 100 líneas arriba del for\n...",
        "autofix": "No",
    },
    "0x2008h": {
        "codigo": "0x2008h",
        "alias": "GAFF030",
        "titulo": "Los valores de retorno deben definirse como constantes o enum",
        "descripcion": "Reemplazar códigos de retorno numéricos mágicos por constantes descriptivas o enum.",
        "ejemplo_correcto": "return ESTADO_OK;\nreturn ERROR_PARAMETRO_INVALIDO;",
        "ejemplo_incorrecto": "return 1;\nreturn -1;",
        "autofix": "No",
    },
    "0x2009h": {
        "codigo": "0x2009h",
        "alias": "GAFF031",
        "titulo": "Los ejercicios deben ser resueltos mediante funciones",
        "descripcion": "No colocar toda la lógica del problema dentro de la función main(). Modularizar en funciones.",
        "ejemplo_correcto": "int main(void) { procesar_datos(); return 0; }",
        "ejemplo_incorrecto": "int main(void) { // 80 líneas con toda la lógica del ejercicio\n}",
        "autofix": "No",
    },
    "0x200Ah": {
        "codigo": "0x200Ah",
        "alias": "GAFF032",
        "titulo": "Nombres de funciones deben usar snake_case en minúsculas",
        "descripcion": "Los identificadores de función deben estar en snake_case.",
        "ejemplo_correcto": "int calcular_total(int base, int impuesto);",
        "ejemplo_incorrecto": "int CalcularTotal(int Base, int Impuesto);",
        "autofix": "No",
    },

    # 0x30XXh: Punteros y Gestión de Memoria
    "0x3001h": {
        "codigo": "0x3001h",
        "alias": "GAFF033",
        "titulo": "Siempre verificá la asignación exitosa de memoria dinámica",
        "descripcion": "Comprobar siempre if (ptr == NULL) tras llamar a malloc, calloc o realloc.",
        "ejemplo_correcto": "ptr = malloc(sizeof(*ptr));\nif (ptr == NULL) {\n    return NULL;\n}",
        "ejemplo_incorrecto": "ptr = malloc(sizeof(*ptr));\nptr->dato = 10; // Falla si no hay memoria",
        "autofix": "No",
    },
    "0x3002h": {
        "codigo": "0x3002h",
        "alias": "GAFF034",
        "titulo": "Asigná NULL al puntero tras free() para evitar punteros colgantes",
        "descripcion": "Hacer ptr = NULL inmediatamente tras free(ptr); para evitar dangling pointers.",
        "ejemplo_correcto": "free(ptr);\nptr = NULL;",
        "ejemplo_incorrecto": "free(ptr);\n// ptr sigue apuntando a memoria liberada",
        "autofix": "No",
    },
    "0x3003h": {
        "codigo": "0x3003h",
        "alias": "GAFF035",
        "titulo": "No mezcles asignación y comparación en una sola línea",
        "descripcion": "Separar la asignación de memoria de la comparación contra NULL.",
        "ejemplo_correcto": "ptr = malloc(tamano);\nif (ptr == NULL) { ... }",
        "ejemplo_incorrecto": "if ((ptr = malloc(tamano)) == NULL) { ... }",
        "autofix": "No",
    },
    "0x3004h": {
        "codigo": "0x3004h",
        "alias": "GAFF002",
        "titulo": "Utilizá typedef para definir tipos de estructuras con el sufijo _t",
        "descripcion": "Los tipos creados mediante typedef (structs, enums, unions) deben identificarse con sufijo '_t' (o prefijo 't_').",
        "ejemplo_correcto": "typedef struct nodo nodo_t;\ntypedef enum estado estado_t;",
        "ejemplo_incorrecto": "typedef struct nodo Nodo;",
        "autofix": "No",
    },
    "0x3005h": {
        "codigo": "0x3005h",
        "alias": "GAFF036",
        "titulo": "Minimizá el uso de múltiples niveles de indirección (***ptr)",
        "descripcion": "Evitar punteros triples o niveles de indirección innecesariamente complejos.",
        "ejemplo_correcto": "int *obtener_datos(size_t *tamano);",
        "ejemplo_incorrecto": "void obtener_datos(int ***ptr_datos);",
        "autofix": "No",
    },
    "0x3006h": {
        "codigo": "0x3006h",
        "alias": "GAFF037",
        "titulo": "Documentá la propiedad de los recursos al utilizar punteros",
        "descripcion": "Indicar explícitamente en el contrato quién es responsable de liberar la memoria.",
        "ejemplo_correcto": "/** @return Puntero asignado. El llamador debe liberar con free(). */",
        "ejemplo_incorrecto": "char *crear_cadena();",
        "autofix": "No",
    },
    "0x3007h": {
        "codigo": "0x3007h",
        "alias": "GAFF038",
        "titulo": "Argumentos puntero de solo lectura deben ser const",
        "descripcion": "Calificar con const los punteros cuyos datos apuntados no son modificados por la función.",
        "ejemplo_correcto": "void imprimir_texto(const char *cadena);",
        "ejemplo_incorrecto": "void imprimir_texto(char *cadena);",
        "autofix": "No",
    },
    "0x3008h": {
        "codigo": "0x3008h",
        "alias": "GAFF039",
        "titulo": "Punteros nulos deben ser inicializados y comparados con NULL",
        "descripcion": "Usar explícitamente NULL en lugar del literal 0 para punteros.",
        "ejemplo_correcto": "int *ptr = NULL;\nif (ptr == NULL) { ... }",
        "ejemplo_incorrecto": "int *ptr = 0;\nif (ptr == 0) { ... }",
        "autofix": "No",
    },
    "0x3009h": {
        "codigo": "0x3009h",
        "alias": "GAFF040",
        "titulo": "Documentá explícitamente los casos en que una función puede retornar NULL",
        "descripcion": "Aclarar en la documentación si el retorno NULL indica error o fin de búsqueda.",
        "ejemplo_correcto": "/** @return Puntero al elemento, o NULL si no existe. */",
        "ejemplo_incorrecto": "nodo_t *buscar(int id);",
        "autofix": "No",
    },
    "0x300Ah": {
        "codigo": "0x300Ah",
        "alias": "GAFF041",
        "titulo": "Utilizá cast explícito al convertir tipos de punteros",
        "descripcion": "Evitar conversiones implícitas incompatibles entre diferentes tipos de punteros.",
        "ejemplo_correcto": "int *ptr = (int *)mem;",
        "ejemplo_incorrecto": "int *ptr = mem;",
        "autofix": "No",
    },
    "0x300Bh": {
        "codigo": "0x300Bh",
        "alias": "GAFF042",
        "titulo": "Usá siempre sizeof en asignaciones dinámicas (prefiriendo sizeof(*ptr))",
        "descripcion": "Evitar tamaños fijos calculados a mano en malloc/calloc.",
        "ejemplo_correcto": "ptr = malloc(sizeof(*ptr));",
        "ejemplo_incorrecto": "ptr = malloc(4);",
        "autofix": "No",
    },
    "0x300Ch": {
        "codigo": "0x300Ch",
        "alias": "GAFF043",
        "titulo": "Verificá siempre los límites de los arreglos antes de acceder a sus elementos",
        "descripcion": "Validar índices de arreglos para evitar desbordamientos de búfer (out-of-bounds).",
        "ejemplo_correcto": "if (indice >= 0 && indice < TAMANO) { arr[indice] = x; }",
        "ejemplo_incorrecto": "arr[indice] = x; // Sin chequear si indice < TAMANO",
        "autofix": "No",
    },
    "0x300Dh": {
        "codigo": "0x300Dh",
        "alias": "GAFF006",
        "titulo": "Utilizá enum o constantes en lugar de números mágicos",
        "descripcion": "No utilizar literales numéricos sin contexto en el cuerpo del código (distintos de 0, 1, 2, -1). Definir constantes con #define o enum.",
        "ejemplo_correcto": "#define MAX_INTENTOS 5\nfor (int i = 0; i < MAX_INTENTOS; i++)",
        "ejemplo_incorrecto": "for (int i = 0; i < 5; i++) // ¿Qué significa 5?",
        "autofix": "No",
    },
    "0x300Eh": {
        "codigo": "0x300Eh",
        "alias": "GAFF044",
        "titulo": "Documentá el comportamiento de las funciones ante punteros nulos",
        "descripcion": "Especificar si una función tolera parámetros NULL o aborta con aserción.",
        "ejemplo_correcto": "/** @param ptr Puntero al recurso (no debe ser NULL). */",
        "ejemplo_incorrecto": "void procesar(nodo_t *ptr);",
        "autofix": "No",
    },
    "0x300Fh": {
        "codigo": "0x300Fh",
        "alias": "GAFF045",
        "titulo": "Liberá la memoria en el orden inverso a su asignación (deep free)",
        "descripcion": "Liberar los miembros dinámicos antes de liberar la estructura contenedora.",
        "ejemplo_correcto": "free(nodo->nombre);\nfree(nodo);",
        "ejemplo_incorrecto": "free(nodo);\n// nodo->nombre quedó huérfano (leak)",
        "autofix": "No",
    },
    "0x3010h": {
        "codigo": "0x3010h",
        "alias": "GAFF046",
        "titulo": "Variables de tamaños o índices deben ser de tipo size_t",
        "descripcion": "Utilizar size_t en lugar de int con signo para longitudes e iteradores de arreglos.",
        "ejemplo_correcto": "size_t longitud = strlen(cadena);",
        "ejemplo_incorrecto": "int longitud = strlen(cadena);",
        "autofix": "No",
    },
    "0x3011h": {
        "codigo": "0x3011h",
        "alias": "GAFF047",
        "titulo": "Si una función recibe un puntero genérico de solo lectura, usar const void*",
        "descripcion": "Firmar funciones con const void* cuando no se modifiquen los bytes leídos.",
        "ejemplo_correcto": "void imprimir_hex(const void *buffer, size_t n);",
        "ejemplo_incorrecto": "void imprimir_hex(void *buffer, size_t n);",
        "autofix": "No",
    },
    "0x0035h": {
        "codigo": "0x0035h",
        "alias": "GAFF048",
        "titulo": "Diseñá los Tipos de Datos Abstractos utilizando punteros opacos",
        "descripcion": "Ocultar los detalles de implementación de structs en archivos .h mediante punteros incompletos.",
        "ejemplo_correcto": "typedef struct lista_t lista_t; // En lista.h",
        "ejemplo_incorrecto": "struct lista_t { nodo_t *cabeza; }; // En lista.h expone campos internos",
        "autofix": "No",
    },
    "0x0036h": {
        "codigo": "0x0036h",
        "alias": "GAFF049",
        "titulo": "Asigná NULL al puntero tras liberar un recurso opaco",
        "descripcion": "Asignar NULL al puntero en el cliente tras destruir un TDA para prevenir accesos inválidos.",
        "ejemplo_correcto": "lista_destruir(mi_lista);\nmi_lista = NULL;",
        "ejemplo_incorrecto": "lista_destruir(mi_lista);",
        "autofix": "No",
    },

    # 0x40XXh: Gestión de Archivos y Errores
    "0x4001h": {
        "codigo": "0x4001h",
        "alias": "GAFF050",
        "titulo": "Manejá correctamente la apertura y cierre de archivos",
        "descripcion": "Validar if (archivo == NULL) tras fopen y asegurar el cierre con fclose.",
        "ejemplo_correcto": "FILE *f = fopen(\"datos.txt\", \"r\");\nif (f == NULL) return -1;\n...\nfclose(f);",
        "ejemplo_incorrecto": "FILE *f = fopen(\"datos.txt\", \"r\");\nfread(buf, 1, 10, f); // Si f es NULL rompe",
        "autofix": "No",
    },
    "0x4002h": {
        "codigo": "0x4002h",
        "alias": "GAFF051",
        "titulo": "Validá los retornos de lectura y escritura de archivos",
        "descripcion": "Verificar los valores de retorno de fread, fwrite, fgets, fscanf.",
        "ejemplo_correcto": "size_t leidos = fread(buf, 1, 100, f);\nif (leidos < 100) { ... }",
        "ejemplo_incorrecto": "fread(buf, 1, 100, f); // Sin verificar si leyó",
        "autofix": "No",
    },
    "0x4003h": {
        "codigo": "0x4003h",
        "alias": "GAFF052",
        "titulo": "Utilizá errno, perror y strerror para reportar fallos",
        "descripcion": "Diagnosticar fallos de archivos mediante perror o strerror(errno).",
        "ejemplo_correcto": "if (f == NULL) { perror(\"Error al abrir archivo\"); }",
        "ejemplo_incorrecto": "if (f == NULL) { printf(\"Error\\n\"); }",
        "autofix": "No",
    },
    "0x4004h": {
        "codigo": "0x4004h",
        "alias": "GAFF053",
        "titulo": "Asegurá la simetría de recursos al abrir y cerrar archivos",
        "descripcion": "Abrir y cerrar descriptores de archivos dentro del mismo nivel de abstracción funcional.",
        "ejemplo_correcto": "void procesar() { FILE *f = fopen(...); ... fclose(f); }",
        "ejemplo_incorrecto": "FILE *f = fopen(...); delegar(f); // Nadie cierra f",
        "autofix": "No",
    },
    "0x4005h": {
        "codigo": "0x4005h",
        "alias": "GAFF054",
        "titulo": "Evitá offsets fijos codificados a mano sin validar dimensiones",
        "descripcion": "Comprobar el tamaño real del archivo antes de posicionar punteros con fseek.",
        "ejemplo_correcto": "if (offset < tamano_archivo) { fseek(f, offset, SEEK_SET); }",
        "ejemplo_incorrecto": "fseek(f, 1000, SEEK_SET);",
        "autofix": "No",
    },

    # 0x50XXh: Compilación y Buenas Prácticas
    "0x5001h": {
        "codigo": "0x5001h",
        "alias": "GAFF055",
        "titulo": "Arreglos estáticos con tamaño fijo en compilación (prohibido VLA)",
        "descripcion": "Los arreglos de longitud variable (int arr[n]) están prohibidos; usar constantes (#define) o malloc.",
        "ejemplo_correcto": "#define TAMANO 100\nint arr[TAMANO];",
        "ejemplo_incorrecto": "int n = 100;\nint arr[n]; // VLA prohibido",
        "autofix": "No",
    },
    "0x5002h": {
        "codigo": "0x5002h",
        "alias": "GAFF056",
        "titulo": "Desarrollá y compilá siempre con todas las advertencias activadas",
        "descripcion": "Compilar con -Wall -Wextra -Werror -pedantic para detectar anomalías tempranas.",
        "ejemplo_correcto": "CFLAGS = -Wall -Wextra -Werror -pedantic -std=c11",
        "ejemplo_incorrecto": "gcc main.c -o app",
        "autofix": "No",
    },
    "0x5003h": {
        "codigo": "0x5003h",
        "alias": "GAFF005",
        "titulo": "Utilizá guardas de inclusión en todos los archivos de cabecera",
        "descripcion": "Todo archivo de cabecera (.h) debe incluir guardas de preprocesador (#ifndef ARCHIVO_H / #define ARCHIVO_H / #endif) o #pragma once.",
        "ejemplo_correcto": "#ifndef LISTA_H\n#define LISTA_H\n...\n#endif /* LISTA_H */",
        "ejemplo_incorrecto": "Archivo lista.h sin guardas de inclusión.",
        "autofix": "Sí",
    },
    "0x5004h": {
        "codigo": "0x5004h",
        "alias": "GAFF057",
        "titulo": "Todas las operaciones con cadenas deben ser seguras",
        "descripcion": "Utilizar snprintf o strncpy en lugar de strcpy/strcat sin límite de tamaño para prevenir buffer overflows.",
        "ejemplo_correcto": "snprintf(dest, sizeof(dest), \"%s\", orig);",
        "ejemplo_incorrecto": "strcpy(dest, orig);\nstrcat(dest, extra);",
        "autofix": "No",
    },
    "0x5005h": {
        "codigo": "0x5005h",
        "alias": "GAFF058",
        "titulo": "Organizá la estructura de tus archivos .c de forma estándar",
        "descripcion": "Estructurar los archivos con includes, defines, typedefs, prototipos y funciones en orden predecible.",
        "ejemplo_correcto": "1. #includes\n2. #defines\n3. typedefs\n4. Prototipos static\n5. Implementaciones",
        "ejemplo_incorrecto": "Declarar funciones antes de includes o mezclar defines en el medio del archivo.",
        "autofix": "No",
    },
    "0x5006h": {
        "codigo": "0x5006h",
        "alias": "GAFF059",
        "titulo": "Preferí fgets sobre gets y scanf para leer cadenas",
        "descripcion": "La función gets() está prohibida y scanf(\"%s\") no valida desbordamientos.",
        "ejemplo_correcto": "fgets(buffer, sizeof(buffer), stdin);",
        "ejemplo_incorrecto": "gets(buffer);\nscanf(\"%s\", buffer);",
        "autofix": "No",
    },
}

# Alias bidireccionales para retrocompatibilidad
ALIAS_MAP: Dict[str, str] = {
    "GAFF000": "0x0000h",
    "GAFF001": "0x0007h",
    "GAFF002": "0x3004h",
    "GAFF003": "0x2004h",
    "GAFF004": "0x2005h",
    "GAFF005": "0x5003h",
    "GAFF006": "0x300Dh",
    "GAFF007": "0x0004h",
    "GAFF008": "0x1006h",
    "GAFF009": "0x0009h",
    "GAFF010": "0x0005h",
    "GAFF011": "0x0001h",
    "GAFF012": "0x0002h",
    "GAFF013": "0x0003h",
    "GAFF014": "0x0006h",
    "GAFF015": "0x0008h",
    "GAFF016": "0x000Ah",
    "GAFF017": "0x000Bh",
    "GAFF018": "0x1001h",
    "GAFF019": "0x1002h",
    "GAFF020": "0x1003h",
    "GAFF021": "0x1004h",
    "GAFF022": "0x1005h",
    "GAFF023": "0x1007h",
    "GAFF024": "0x1008h",
    "GAFF025": "0x2001h",
    "GAFF026": "0x2002h",
    "GAFF027": "0x2003h",
    "GAFF028": "0x2006h",
    "GAFF029": "0x2007h",
    "GAFF030": "0x2008h",
    "GAFF031": "0x2009h",
    "GAFF032": "0x200Ah",
    "GAFF033": "0x3001h",
    "GAFF034": "0x3002h",
    "GAFF035": "0x3003h",
    "GAFF036": "0x3005h",
    "GAFF037": "0x3006h",
    "GAFF038": "0x3007h",
    "GAFF039": "0x3008h",
    "GAFF040": "0x3009h",
    "GAFF041": "0x300Ah",
    "GAFF042": "0x300Bh",
    "GAFF043": "0x300Ch",
    "GAFF044": "0x300Eh",
    "GAFF045": "0x300Fh",
    "GAFF046": "0x3010h",
    "GAFF047": "0x3011h",
    "GAFF048": "0x0035h",
    "GAFF049": "0x0036h",
    "GAFF050": "0x4001h",
    "GAFF051": "0x4002h",
    "GAFF052": "0x4003h",
    "GAFF053": "0x4004h",
    "GAFF054": "0x4005h",
    "GAFF055": "0x5001h",
    "GAFF056": "0x5002h",
    "GAFF057": "0x5004h",
    "GAFF058": "0x5005h",
    "GAFF059": "0x5006h",
}

for k, v in ALIAS_MAP.items():
    if v in CATALOGO_REGLAS:
        CATALOGO_REGLAS[k] = CATALOGO_REGLAS[v]
